# Generated by Django 6.0.2 on 2026-04-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_type",
            field=models.CharField(
                choices=[("enquiry", "Enquiry"), ("order", "Order")],
                default="order",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_mode",
            field=models.CharField(
                blank=True,
                choices=[("air", "Air"), ("sea", "Sea")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("responded", "Responded"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="supplier_response",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
