# Generated by Django 6.0.2 on 2026-04-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="logistics",
            name="shipping_mode",
            field=models.CharField(
                blank=True,
                choices=[("air", "Air"), ("sea", "Sea")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="logistics",
            name="tracking_stage",
            field=models.CharField(
                choices=[
                    ("supplier", "Supplier"),
                    ("warehouse", "Warehouse"),
                    ("transport", "Transport"),
                    ("delivery", "Delivery"),
                    ("final_destination", "Final Destination"),
                ],
                default="supplier",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="logistics",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("in_transit", "In Transit"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
